### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by hackwater** [firefox-devtools/react-contextmenu#143]
Hi! I was wondering if it would be possible to get a patch release to NPM containing the React 18-compatible types we merged in about a month ago ([in this commit](https://github.com/firefox-devtools/react-contextmenu/commit/5b6995b766355bb33ae0870d645c253b2820d248)). Apologies in advance if this is not the right way to make such a request.

Thanks!

**Comment by julienw** [comment]
Thanks for the reminder, let me do that now!

**Comment by julienw** [comment]
https://github.com/firefox-devtools/react-contextmenu/releases/tag/v5.1.1
